name: "Admin panel CI"

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: SSH Execute Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        debug: true
        script: |
          cd ${{ secrets.PROJECT_FOLDER }};
          echo '--- LIST OF FILES ---';
          ls -al;
          echo '--- GIT CHECKOUT ---';
          git checkout stage;
          git pull origin stage;
          echo '--- DOCKER COMPOSE DOWN ---';
          docker-compose --file docker-compose.yml down;
          echo '--- DOCKER COMPOSE UP ---';
          docker-compose --file docker-compose.yml up -d;
          docker system prune --all --force;
