name: "Admin panel CI"

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Up docker compose on server
      uses: D3rHase/ssh-command-action@{version}
      with:
        host: ${{secrets.HOST}} 
        user: ${{secrets.USER}} 
        private_key: ${{secrets.PRIVATE_KEY}} 
        command: |
          cd ${{ secrets.PROJECT_FOLDER }};
          echo '--- LIST OF FILES ---';
          ls -al;
          echo '--- GIT CHECKOUT ---';
          git checkout stage;
          git pull;
          docker-compose --file docker-compose.yml down;
          docker-compose --file docker-compose.yml up -d;
          docker system prune --all --force;

